### ISSUE TITLE
Error Classes: tracking issue

### ISSUE THREAD

**Issue by marcvanzee** [google/flax#957]
This is a tracking issue for the effort of raising custom error classes in Flax and documenting them property. 

Below is a TODO list.

- [x] Start using `errors.py` for custom error messages and make sure they are documented on RTD (#949)
- [x] Move all of our error messages to `errrors.py`. We should make a clear separation between user-face errors (which should provide clear error messages using these error classes) and internal assertions (which can be one-liners, but shouldn't be exposed to the average user).
- [x] Make sure each error type is tested, ensuring that indeed the right error class is raised under each situation.
- [x] Improve error messages guided by the other issues in milestone ["Improve Error Messages"](https://github.com/google/flax/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Improve+Error+Messages%22) .

**Comment by marcvanzee** [comment]
Closing this since after #1072 the bulk of the work is done.
